import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { updateCompanyAction } from "@/modules/core/actions";
import { requireUser } from "@/modules/core/authz";

export default async function CompanyDetailPage({ params }: { params: { id: string } }) {
  const user = await requireUser();
  const [company, users] = await Promise.all([prisma.company.findFirst({ where: { id: params.id, organizationId: user.organizationId, deletedAt: null }, include: { contacts: true, opportunities: true } }), prisma.user.findMany({ where: { organizationId: user.organizationId, deletedAt: null, isActive: true }, orderBy: { name: "asc" } })]);
  if (!company) notFound();
  return <main className="p-6"><form action={updateCompanyAction.bind(null, company.id, { status: "idle" })} className="mx-auto max-w-2xl space-y-3 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold text-serviscon-navy">Editar empresa</h2><input name="legalName" defaultValue={company.legalName} required className="w-full rounded-xl border px-4 py-3" /><input name="tradeName" defaultValue={company.tradeName ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="document" defaultValue={company.document ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="segment" defaultValue={company.segment ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="phone" defaultValue={company.phone ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="email" defaultValue={company.email ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="website" defaultValue={company.website ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="address" defaultValue={company.address ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="city" defaultValue={company.city ?? ""} className="w-full rounded-xl border px-4 py-3" /><input name="state" defaultValue={company.state ?? ""} className="w-full rounded-xl border px-4 py-3" /><select name="ownerId" defaultValue={company.ownerId ?? ""} className="w-full rounded-xl border px-4 py-3"><option value="">Responsável</option>{users.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><textarea name="notes" defaultValue={company.notes ?? ""} className="w-full rounded-xl border px-4 py-3" /><button className="rounded-xl bg-serviscon-blue px-4 py-3 font-semibold text-white" type="submit">Salvar</button><p className="text-sm text-slate-500">{company.contacts.length} contatos e {company.opportunities.length} oportunidades vinculadas.</p></form></main>;
}
