import { prisma } from "@/lib/prisma";
import { ensureDefaultPipelineStagesAction, updateOrganizationAction } from "@/modules/core/actions";
import { requirePermission } from "@/modules/core/authz";

export default async function SettingsPage() {
  const user = await requirePermission("SETTINGS_MANAGE");
  const [organization, users, stages] = await Promise.all([
    prisma.organization.findUniqueOrThrow({ where: { id: user.organizationId } }),
    prisma.user.findMany({ where: { organizationId: user.organizationId, deletedAt: null }, orderBy: { name: "asc" } }),
    prisma.pipelineStage.findMany({ where: { organizationId: user.organizationId, deletedAt: null }, orderBy: { position: "asc" } }),
  ]);
  return <main className="space-y-6 p-6"><header><h2 className="text-3xl font-bold text-serviscon-navy">Configurações</h2><p className="text-slate-600">Acesso permitido para ADMIN e MANAGER conforme RBAC.</p></header><section className="grid gap-6 xl:grid-cols-2"><form action={updateOrganizationAction.bind(null, { status: "idle" })} className="space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold text-serviscon-navy">Dados da organização</h3><input name="name" defaultValue={organization.name} className="w-full rounded-xl border px-4 py-3" /><button className="rounded-xl bg-serviscon-blue px-4 py-3 font-semibold text-white" type="submit">Salvar organização</button></form><article className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold text-serviscon-navy">Perfis e permissões</h3><div className="mt-4 space-y-2 text-sm text-slate-600"><p>ADMIN: acesso total.</p><p>MANAGER: dashboard, relatórios e configurações.</p><p>MARKETING, COMMERCIAL e OPERATIONS: acesso operacional sem configurações administrativas.</p></div></article></section><section className="grid gap-6 xl:grid-cols-2"><article className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-semibold text-serviscon-navy">Usuários</h3><div className="mt-4 space-y-3">{users.map((appUser) => <div key={appUser.id} className="rounded-xl bg-slate-50 px-4 py-3 text-sm"><strong>{appUser.name}</strong><br /><span className="text-slate-500">{appUser.email} · {appUser.role}</span></div>)}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><h3 className="font-semibold text-serviscon-navy">Etapas do pipeline</h3><form action={ensureDefaultPipelineStagesAction}><button className="rounded-xl border px-3 py-2 text-sm" type="submit">Criar etapas padrão</button></form></div><div className="mt-4 space-y-3">{stages.length === 0 ? <p className="text-sm text-slate-600">Nenhuma etapa configurada.</p> : stages.map((stage) => <div key={stage.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><span>{stage.position}. {stage.name}</span><strong>{stage.kind}</strong></div>)}</div></article></section></main>;
}
